### ISSUE TITLE
TOTP with 12 digits causes crash

### ISSUE THREAD

**Issue by eender** [calleluks/Tofu#40]
So I was testing a few 2FA apps and just to mess around I created a QR code with this website:
https://freeotp.github.io/qrcode.html

This is just an example:
![chrome_2020-05-07_18-33-57](https://user-images.githubusercontent.com/8578053/81320593-b9cb7d80-9091-11ea-9ab4-83714251a1ef.png)

**!! Don't try to scan this code !!, it will most likely make tofu unusable !**

After scanning this with Tofu, the app instantly crashes. And even after deleting and reinstalling the app: I cannot open Tofu! It simply crashes.

I also tried deleting the app, restarting the device and reinstalling the app. No difference.

Tested Tofu Version 1.8 with an iPhone 8 on 13.4.1
Also tried this with an iPhone 6s on 13.4.1

**Comment by calleerlandsson** [comment]
Thanks for reporting this @eender, and thanks for writing up a fix @benbusby! Let's continue the discussion on #41.

**Comment by eender** [comment]
I just wanted to give you a quick feedback. Unfortunately, no update has been released so far that solves this problem. That would mean that to this day I can't rely on tofu, because I simply can't open it.

**Comment by calleerlandsson** [comment]
Sorry about that @eender. I'll look at it whenever I get a chance.

**Comment by calleluks** [comment]
Hey @eender, I finally got a chance to look at this. Fixed in f43b08dce887226ff2f13dc0eb0b9b8a1bb2770e, 7a94ba60fbc414a7fe4f74810d45ab15e6adda1a, and 1680d09e65962bf8089ec397b52a42efe6a59f43.

I've also pushed a new beta version (1.10 (13)) to TestFlight. Use this link to join the beta program if you want to help test it! https://testflight.apple.com/join/LLe6CFdo

**Comment by eender** [comment]
Thanks, I can confirmed that the newest beta fixed this problem.
