### ISSUE TITLE
Additional icon requests

### ISSUE THREAD

**Issue by akerl** [calleluks/Tofu#6]
Hi! Like the other issue reporter, also wanted to say I love the app!

Not sure if, longer-term, you'd prefer one mega-issue for tracking icon requests, or split (side idea: maybe make it possible for users to add their own icons? More code work, but could spare you from crazy esoteric requests and would rock for things like AWS, where I have 8 different TOTP rows)

My requests, just based on the stuff I've got in the app now:
* Coinbase
* Kickstarter
* "Amazon Web Services" (you currently have an icon for AWS, but the AWS tokens add themselves as "Amazon Web Services", which doesn't match. Changing the token info to AWS makes the icon show up)
* Name.com

**Comment by calleerlandsson** [comment]
Hey @akerl, I'm happy you're enjoying the app! 😄

> side idea: maybe make it possible for users to add their own icons? More code work, but could spare you from crazy esoteric requests and would rock for things like AWS, where I have 8 different TOTP rows

I think this is a great idea! I've thought about it a bit in the past but I haven't figured out where people would add icons from. Would it be from the camera roll/photos? It seems a bit cumbersome, especially if they also have to prepare the images in specific dimensions. Do you have any thoughts on this?

I'll do my best to include the icons you requested in the next release. I'm afraid it will take some time until I have it ready, though, since I'm currently a bit overwhelmed with freelance work.

**Comment by akerl** [comment]
My rough plan is to put my time where my mouth is and see about PRing in some icons when I get home tonight :)

I imagine I'll just look at the current icons for format/dimensions.

I agree that pulling from photos would be cumbersome, but I'd consider it an advanced option. A bit cumbersome for the user, but would let them freely customize, and with any luck it's not something they'd be doing often.

Another option that just occurred to me: maybe break icons out into a separate repo / artifact? I've got essentially 0 knowledge about Swift / iOS dev, but if I think from the perspective of other programming, maybe it makes sense to pull the icons from a "tofu-icons" github repo (or a tarball generated from such a repo). That opens up 2 options:

* For you, accepting icon PRs doesn't require a new app release, just merging a new icon into that other repo
* There's the possibility to expose the repo as a tunable in Settings. So if I want custom icons, I fork your repo, add whatever icons I want, and then tell the app to use that for icon artifacts.

The latter might be nuts because of the added implications of pulling from potentially untrusted user input.

**Comment by frozenshadow** [comment]
Besides programmer I am also a graphic designer, maybe I can make some icons too.
And besides the camera roll option, it would also make sense to make use of the documents options in iTunes.

Then you have two possibilities for the naming convention:
1. github.png = GitHub, wordpress.png = Wordpress etc.
2. Select icon in-app (this could off course also be the camera roll)

Let me know what you think and if and how I can help :)

**Comment by calleerlandsson** [comment]
@akerl:

> My rough plan is to put my time where my mouth is and see about PRing in some icons when I get home tonight :)
> 
> I imagine I'll just look at the current icons for format/dimensions.

This would be great! In the project root, there's [a Sketch file](https://github.com/calleerlandsson/Tofu/blob/634fe357634fcea56151f09cb9d2738542bf929a/IssuerIcons.sketch) with all of the current icons. The easiest thing is probably to copy the row of placeholder icons, renaming the group and icons, adding the artwork and then exporting them using the already set up export formats.

> Another option that just occurred to me: maybe break icons out into a separate repo / artifact? I've got essentially 0 knowledge about Swift / iOS dev, but if I think from the perspective of other programming, maybe it makes sense to pull the icons from a "tofu-icons" github repo (or a tarball generated from such a repo). That opens up 2 options:
> 
> For you, accepting icon PRs doesn't require a new app release, just merging a new icon into that other repo
> There's the possibility to expose the repo as a tunable in Settings. So if I want custom icons, I fork your repo, add whatever icons I want, and then tell the app to use that for icon artifacts.
> The latter might be nuts because of the added implications of pulling from potentially untrusted user input.

I have considered it in the past but am hesitant to add networking code and external service dependencies to the app since I think the lack of networking code is a "feature" and that I'm not a big fan of maintaining the hosting for the artifacts. If they can be hosted on GitHub, I guess that wouldn't be a big hassle, though.

@frozenshadow:

> Besides programmer I am also a graphic designer, maybe I can make some icons too.

Let me know how I can help you out!

> And besides the camera roll option, it would also make sense to make use of the documents options in iTunes.

I think this is an interesting option.

Here are some possible steps towards letting users add their own icons:

1. For any given account, in addition to automatically selecting an icon based on the issuer name, also let the user manually select one from all bundled icons.
2. Also let the user select icons added as documents through iTunes
3. Also let users add icons from their camera roll

I won't have time to implement this in the near future so if someone else would like to pick it up, I'd be happy to answer questions! If not, I'll get to it whenever I have time.

**Comment by eutampieri** [comment]
I think icons could be added by bringing up a screen where the name provided is searched in some api like bing images and the user is able to select from a grid the icon that best suits its needs.
PS: this app is good because of its clean interface… keep working!

**Comment by eutampieri** [comment]
Here it is:
https://dev.cognitive.microsoft.com/docs/services/56b43f0ccf5ff8098cef3808/operations/56b4433fcf5ff8098cef380c

**Comment by jooize** [comment]
Import from Document Providers and Photo Library (make it so the app doesn’t get full read access to photos). iTunes is a horrible way to transfer into an app.

People use services that you won’t ever have icons for. Please enable custom icons.

Thanks for making Tofu. I have many ideas I’ll post over time. Using MFA many times every day has made me think the process through.

**Comment by captn3m0** [comment]
I found the thumbnails in andOTP pretty helpful: https://github.com/andOTP/andOTP/tree/master/app/src/main/res/drawable

It has some default generic icons as well, which you can assign to your custom mail provider, for eg.

**Comment by yoiang** [comment]
@calleerlandsson for icon submissions would you prefer each icon be a different PR, different commit, or all bundled together and articulated in the commit message?

**Comment by calleerlandsson** [comment]
Hey @yoiang, as long as the commit messages are clear, both are fine with me.

**Comment by TCB13** [comment]
We're also missing an icon for Twitter and another for Bitstamp! Keep up the great work.
