### ISSUE TITLE
Exporting Codes

### ISSUE THREAD

**Issue by p-marg** [calleluks/Tofu#86]
What if we switch from an Apple device over to Android, there is no way for us export our codes.

**Comment by samlitt** [comment]
I would also appreciate this feature, since I am considering switching to Android.

So ultimately a universal file type for this data should be established, but as a work around the single OTP' could be displayed as QR-codes in order to be scanned by the new device. A special file type would be preferred in order to make backups and import the OTP data even when the original device fails, gets lost etc.

**Comment by calleluks** [comment]
Thanks for the feedback! I'll close this in favor of #38 since that's how I aim to cater to this need.
